import "./App.css";
import "./tasks/1";
import "./tasks/2";
import "./tasks/3";
import "./tasks/4";
import "./tasks/5";
import "./tasks/6";
import "./tasks/7";
import "./tasks/8";
import "./tasks/9";
import "./tasks/10";
import "./tasks/11";
import "./tasks/12";
import "./tasks/13";
import "./tasks/14";
import "./tasks/15";
import "./tasks/16";
import "./tasks/17";
import "./tasks/18";
import "./tasks/19";
import "./tasks/20";
import "./tasks/21";
import "./tasks/22";
import "./tasks/23";
import "./tasks/24";
import "./tasks/25";
import "./tasks/26";
import "./tasks/27";
import "./tasks/28";
import "./tasks/29";
import "./tasks/30";
import "./tasks/31";
import "./tasks/32";
import "./tasks/33";
import "./tasks/34";
import "./tasks/35";
import "./tasks/36";
import "./tasks/37";
import "./tasks/38";
import "./tasks/39";
import "./tasks/40";
import "./tasks/41";
import "./tasks/42";
import "./tasks/43";
import "./tasks/44";
import "./tasks/45";
import "./tasks/46";
import "./tasks/47";
import "./tasks/48";
import "./tasks/49";
import "./tasks/50";

function App() {
  return <div className="App"></div>;
}

export default App;
